### ISSUE TITLE
Paginación ir arriba / Pagination go top

### ISSUE THREAD

**Issue by martinacostadev** [okbel/diversidad-media#16]
**Español / Spanish:**

Cuando haces clic en otra página, el scroll necesita ir hacia arriba para poder ver los primeros registros. Ya que sino hay que hacer scroll manual hacia arriba de todo.

**Inglés / English:**

When you click in other page, the scroll needs to go up to see the first records. If not, is necessary do manual scroll to top.

**Comment by okbel** [comment]
Thanks for reporting!

**Comment by okbel** [comment]
Merged with https://github.com/okbel/diversidad-media/pull/18
